from datetime import datetime, timedelta
import re
from app.models import StudyPlanResponse

def generate_ics_calendar(plan: StudyPlanResponse) -> str:
    """Generates an RFC 5545 compliant iCalendar string for all study sessions."""
    lines = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "PRODID:-//StudyMind AI//Smart Study Planner//EN",
        "CALSCALE:GREGORIAN",
        "METHOD:PUBLISH",
        f"X-WR-CALNAME:Study Plan - {plan.student_name}",
        "X-WR-TIMEZONE:UTC"
    ]

    for day in plan.daily_schedules:
        for session in day.sessions:
            if not session.time_slot or session.time_slot == "Flexible" or session.duration_minutes <= 0:
                continue

            # Extract start time (e.g. "09:00" from "09:00 - 10:30")
            match = re.search(r"(\d{1,2}):(\d{2})", session.time_slot)
            if not match:
                continue
            
            sh, sm = int(match.group(1)), int(match.group(2))
            
            try:
                date_obj = datetime.strptime(day.date, "%Y-%m-%d")
                start_dt = date_obj.replace(hour=sh, minute=sm)
                end_dt = start_dt + timedelta(minutes=session.duration_minutes)
                
                dtstamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
                dtstart = start_dt.strftime("%Y%m%dT%H%M%S")
                dtend = end_dt.strftime("%Y%m%dT%H%M%S")
                
                summary = f"[{session.subject}] {session.topic}"
                description = f"Goal: {session.actionable_goal}\\nTechnique: {session.recommended_technique}\\nType: {session.activity_type}"
                
                lines.extend([
                    "BEGIN:VEVENT",
                    f"UID:{session.session_id}-{dtstart}@studymind.ai",
                    f"DTSTAMP:{dtstamp}",
                    f"DTSTART:{dtstart}",
                    f"DTEND:{dtend}",
                    f"SUMMARY:{summary}",
                    f"DESCRIPTION:{description}",
                    "STATUS:CONFIRMED",
                    "BEGIN:VALARM",
                    "TRIGGER:-PT10M",
                    "ACTION:DISPLAY",
                    f"DESCRIPTION:Upcoming study session: {summary}",
                    "END:VALARM",
                    "END:VEVENT"
                ])
            except Exception:
                continue

    lines.append("END:VCALENDAR")
    return "\r\n".join(lines)

def generate_markdown_plan(plan: StudyPlanResponse) -> str:
    """Generates an aesthetic Markdown document of the study plan."""
    md = [
        f"# 🎯 Personalized Study Roadmap: {plan.student_name}",
        f"> **Generated by**: StudyMind AI ({plan.source})  ",
        f"> **Readiness Forecast**: {plan.readiness_forecast}  ",
        f"> **Total Study Period**: {plan.total_days} Days | **Total Study Hours**: {plan.total_study_hours} hrs",
        "",
        "## 📌 Executive Summary",
        plan.summary,
        "",
        "## 🗺️ Milestone Phase Roadmap",
    ]

    for p in plan.phases:
        md.append(f"### {p.phase_name} ({p.duration_days})")
        md.append(f"**Focus**: {p.focus}")
        md.append("**Key Milestones**:")
        for m in p.key_milestones:
            md.append(f"- [ ] {m}")
        md.append("")

    md.append("## 🧠 Spaced Repetition Strategy")
    md.append(plan.spaced_repetition_strategy)
    md.append("")

    md.append("## 🛡️ Burnout Prevention Protocols")
    for b in plan.burnout_prevention_tips:
        md.append(f"- {b}")
    md.append("")

    md.append("## 📅 Day-by-Day Master Schedule")
    for day in plan.daily_schedules:
        md.append(f"### Day {day.day_number}: {day.day_of_week} ({day.date}) - *{day.theme}*")
        md.append(f"**Target Hours**: {day.target_hours}h | **Daily Focus Tip**: {day.daily_tip}")
        if day.review_topics:
            md.append(f"**🔄 Spaced Reviews Today**: {', '.join(day.review_topics)}")
        md.append("")
        md.append("| Time Slot | Subject | Topic | Activity | Duration | Actionable Goal |")
        md.append("|---|---|---|---|---|---|")
        for s in day.sessions:
            md.append(f"| {s.time_slot} | {s.subject} | {s.topic} | {s.activity_type} | {s.duration_minutes}m | {s.actionable_goal} |")
        md.append("")

    return "\n".join(md)
